language: generic
sudo: false
dist: trusty
notifications:
  email: false
   
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - libgtest-dev
      - expect
      - libboost-program-options-dev
      - libboost-filesystem-dev

before_script:
  - mkdir GTEST_BUILD
  - cd GTEST_BUILD
  - cmake -DBUILD_SHARED_LIBS=ON /usr/src/gtest
  - make
  - cd -
  
script:
  - mkdir BUILD
  - cd BUILD
  - GTEST_ROOT=../GTEST_BUILD cmake ..
  - make
  - make test

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++ CC=clang CTEST_OUTPUT_ON_FAILURE=1
