set timeout 1

set file "/tmp/test.ps3"
set passwd "asdfqwer"

system "rm -rf $file"

spawn $GPWSAFE -f $file --create

expect {
	"Enter passphrase *" { pass "Spawn" }
	default              { fail "Spawn" }
	timeout              { fail "Spawn: timed out." }
}

send "$passwd\r"

expect {
	"Reenter passphrase *" { pass "Password" }
	default                { fail "Password" }
	timeout                { fail "Password: timed out." }
}

send "$passwd\r"

expect eof
pass "Created OK"
